(function(d){var k,j,l,n,o,t,p,u,v,q,r,h=Array.prototype.slice,s=Object.prototype.hasOwnProperty;d=this.lvping||(this.lvping={});d.debug=!1;d.global=this;d.require=function(a){if(d.debug&&!d.resolve(a))return d.error(""+a+" required but not found")};d.provide=function(a){if(d.debug)return d.log(""+a+" provided")};d.define=function(a,b){var c,e,f,g,i,h;i=a.split(".");i.shift()!=="lvping"&&d.error('name must start with "lvping."');f=i.pop();c=d;e=0;for(h=i.length;e<h;e++)g=i[e],c.hasOwnProperty(g)?
"object"!==d.type(c[g])&&d.error('invalid namespace "lvping.'+i.slice(0,e+1||9E9).join(".")+'"'):c[g]={},c=c[g];c.hasOwnProperty(f)&&d.warn('conflicting name "'+a+'"');return c[f]=b};d.alias=function(){var a,b,c,e,d,g;c=arguments[0];e=arguments[1];b=3<=arguments.length?h.call(arguments,2):[];d=0;for(g=b.length;d<g;d++)a=b[d],c[a]=c[e];return c};d.resolve=function(a){var b;a=a.split(".");for(b=d.global;a.length&&b;)b=b[a.shift()];return b};d.type=function(a){if(a===null)return"null";if(a===void 0)return"undefined";
return Object.prototype.toString.call(a).match(/\w+/g).pop().toLowerCase()};q="String|Number|Boolean|Array|Function|Object|Null|Undefined".split("|");j=function(a,b){return d["is"+a]=function(a){return b===d.type(a)}};p=0;for(u=q.length;p<u;p++)r=q[p],v=r.toLowerCase(),j(r,v);d.extend=function(){var a,b,c,e,f,g,i,m;e=1<=arguments.length?h.call(arguments,0):[];a=d.isBoolean(e[0])&&e.shift();f=e.shift();i=0;for(m=e.length;i<m;i++)if(c=e[i])for(b in c)s.call(c,b)&&(g=c[b],a&&$.isPlainObject(g)&&(g=d.extend(!0,
{},g)),f[b]=g);return f};d.merge=function(){var a,b;b=1<=arguments.length?h.call(arguments,0):[];a=d.isBoolean(b[0])&&b.shift();return d.extend.apply(d,[a,{}].concat(h.call(b)))};d.proxy=function(){var a,b,c;c=arguments[0];b=arguments[1];a=3<=arguments.length?h.call(arguments,2):[];"array"!==d.type(b)&&(b=[b]);return function(){var e,f,g,i;e=1<=arguments.length?h.call(arguments,0):[];e=a.concat(e);g=0;for(i=b.length;g<i;g++)f=b[g],typeof f==="string"&&(f=c[f]),e=f.apply(c,e||[]),g===b.length-1||"array"===
d.type(e)||(e=[e]);return e}};d.mixin=function(){var a,b,c,e,f,g,i,m;f=arguments[0];c=2<=arguments.length?h.call(arguments,1):[];i=0;for(m=c.length;i<m;i++){b=c[i];a=!1;for(e in b)s.call(b,e)&&(g=b[e],e==="init"?a=g:f[e]=g);"function"===d.type(a)&&a.call(f)}return f};d.log=function(){var a,b;a=1<=arguments.length?h.call(arguments,0):[];if(d.debug&&typeof console!=="undefined"&&console!==null&&(b=console.log)!=null&&b.apply)return console.log.apply(console,["lvping.log: "].concat(h.call(a)))};d.warn=
function(){var a,b;a=1<=arguments.length?h.call(arguments,0):[];if(d.debug&&typeof console!=="undefined"&&console!==null&&(b=console.warn)!=null&&b.apply)return console.warn.apply(console,["lvping.warn: "].concat(h.call(a)))};d.error=function(a){throw"lvping.error: "+a;};d.hasOwn=function(a,b){return a.hasOwnProperty(b)};d.getOwn=function(a,b){if(a.hasOwnProperty(b))return a[b]};d.getOrMake=function(a,b,c){return a.hasOwnProperty(b)?a[b]:a[b]=c(b)};d.getOrNew=function(a,b,c){return d.getOrMake(a,
b,function(){return new c})};d.date={format:function(a,b){var c;b==null&&(b=!1);c=[a.getFullYear(),a.getMonth()+1,a.getDate()].join("-");return b?c.replace(/\b(\d)\b/g,"0$1"):c},parse:function(a){a=Date.parse(a.replace(/-/g,"/"));return isNaN(a)?null:new Date(a)}};d.fn={noop:function(){},bind:function(){var a,b,c;c=arguments[0];b=arguments[1];a=3<=arguments.length?h.call(arguments,2):[];return function(){var d;d=1<=arguments.length?h.call(arguments,0):[];return c.apply(b,a.concat(d))}},pass:function(){var a,
b;b=arguments[0];a=2<=arguments.length?h.call(arguments,1):[];return function(){var c;c=1<=arguments.length?h.call(arguments,0):[];return b.apply(this,a.concat(c))}},equal:function(a,b){return a===b},equalTo:function(a){return function(b){return a===b}}};d.array={make:function(a){var b,c,e,f;if(d.isArray(a))return a;f=[];c=0;for(e=a.length;c<e;c++)b=a[c],f.push(b);return f},forEach:function(a,b,c){var d,f,g;c==null&&(c=null);d=0;for(g=a.length;d<g;d++)f=a[d],b.call(c,f,d,a);return a},indexOf:function(a,
b,c){var e;c==null&&(c=0);d.isFunction(b)||(b=d.fn.equalTo(b));e=a.length;c<0&&(c+=e);for(c=Math.max(c,0);c<e;){if(b(a[c],c))return c;++c}return-1},lastIndexOf:function(a,b,c){var e;c==null&&(c=a.length-1);d.isFunction(b)||(b=d.fn.equalTo(b));e=a.length;c<0&&(c+=e);for(c=Math.min(c,e-1);c>-1;){if(b(a[c],c))return c;--c}return-1}};d.string={trim:function(a){return a.replace(/^\s+|\s+$/g,"")},fill:function(a,b){var c;c=d.isFunction(b)?b:function(a){return d.getOwn(b,a,"")};return a.replace(/#\{(\w+)\}/g,
function(a,b){return c(b)})}};k={};t=function(a){var b;b=a.replace(/\.|\*+/g,function(a){switch(a){case ".":return"\\.";case "*":return"\\w+";default:return".*"}});a=[];a.regex=RegExp("^"+b+"$");return a};d.subscribe=function(a,b,c,e){d.getOrMake(k,a,t).push(b=[typeof b==="string"?c[b]:b,c,e]);return{name:a,info:b}};d.unsubscribe=function(a){var b;b=d.getOrCreate(k,a.name);a=d.array.indexOf(b,a.info);return a>-1&&b.splice(a,1)};d.publish=function(a,b){var c,d,f,g,i;for(f in k)if(c=k[f],c.regex.test(a)){g=
0;for(i=c.length;g<i;g++)d=c[g],d[0].call(d[1],a,b,d[2])}return null};n=function(a,b){var c;c=d.getOrNew(a,"_eventTarget_",Object);return d.getOrNew(c,b,Array)};d.eventTarget={fireEvent:function(){var a,b,c,d,f,g;b=arguments[0];a=2<=arguments.length?h.call(arguments,1):[];b=n(this,b);d=!0;f=0;for(g=b.length;f<g;f++)c=b[f],c.apply(this,a)===!1&&(d=!1);return d},addEventListener:function(a,b){return n(this,a).push(b)},removeEventListener:function(a,b){var c,e;c=n(this,a);if((e=d.array.indexOf(c,b))>
-1)return c.splice(e,1)}};d.alias(d.eventTarget,"fireEvent","trigger","triggerHandler");d.alias(d.eventTarget,"addEventListener","on");d.cookie={get:function(a){var b;return(b=document.cookie.match(RegExp("(^|; )"+a+"=([^;]*)")))?decodeURIComponent(b[2]):null},set:function(a,b,c){var e,f,g;c==null&&(c={});if(e=c.expires)d.isNumber(e)?(f=new Date,e=new Date(f.getTime()+864E5*e)):d.isFunction(e.toGMTString)||(e=!1),c.expires=e&&e.toGMTString();b=""+a+"="+encodeURIComponent(b);g=["expires","path","domain",
"secure"];e=0;for(f=g.length;e<f;e++)a=g[e],a in c&&(b+="; "+a+"="+c[a]);return document.cookie=b},remove:function(a,b){return d.cookie.set(a,"deleted",d.merge(b,{expires:-1}))}};l=function(a){var b,c,e,f;switch(d.type(a)){case "object":c=[];for(b in a)s.call(a,b)&&(e=a[b],c.push(""+l(b)+":"+l(e)));return"{"+c.join(",")+"}";case "array":c=[];b=0;for(f=a.length;b<f;b++)e=a[b],c.push(l(e));return"["+c.join(",")+"]";case "string":return c=a.replace(/["\/\\\b\f\n\r\t\u0100-\uffff]/g,function(a){var b;
switch(a){case '"':return'\\"';case "/":return"\\/";case "\\":return"\\\\";case "\u0008":return"\\b";case "\u000c":return"\\f";case "\n":return"\\n";case "\r":return"\\r";case "\t":return"\\t";default:return"\\u"+((b=a.charCodeAt(0))<4096?"0":"")+b.toString(16)}}),'"'+c+'"';case "number":case "boolean":case "null":return a+"";default:return"null"}};d.json={parse:typeof JSON!=="undefined"&&JSON!==null?JSON.parse:function(){return(new Function("return str"))()},stringify:typeof JSON!=="undefined"&&
JSON!==null?JSON.stringify:l};d.Class=function(){var a;if(arguments.length)return(a=d.Class).extend.apply(a,arguments)};o=!1;d.extend(d.Class,{setup:function(a){this.defaults=d.merge(!0,a.defaults,this.defaults);return arguments},extend:function(a,b,c){var e,f,g;typeof a!=="string"&&(g=[a,b,null],b=g[0],c=g[1],a=g[2]);c||(g=[b||{},null],c=g[0],b=g[1]);g=function(){var a;if(!o)return(a=this.klass).newInstance.apply(a,arguments)};a&&d.define(a,g);e=this.rawInstance();f=this.prototype;d.extend(e,c,{klass:g,
constructor:g,base:function(a,b){var c;return(c=f[a])!=null?c.apply(this,b!=null?b:d.array.make(arguments.callee.caller.arguments)):void 0}});d.extend(g,this,b,{fullName:a,prototype:e});e=g.setup.apply(g,[this].concat(d.array.make(arguments)));typeof g.init==="function"&&g.init.apply(g,e||[]);return g},proxy:function(){var a,b;b=arguments[0];a=2<=arguments.length?h.call(arguments,1):[];return d.proxy.apply(d,[this,b].concat(h.call(a)))},mixin:function(){var a;a=1<=arguments.length?h.call(arguments,
0):[];return d.mixin.apply(d,[this.prototype].concat(h.call(a)))},newInstance:function(){var a,b;b=this.rawInstance();b.setup&&(a=b.setup.apply(b,arguments));d.isArray(a)||(a=arguments);b.init&&b.init.apply(b,a);return b},rawInstance:function(){var a;o=!0;a=new this;o=!1;return a}});j=d.Class.proxy;d.Class.callback=j;d.Class.prototype.proxy=j;d.Class.prototype.callback=j;$(function(){var a;a=$.cleanData;return $.cleanData=function(b){var c,d,f;d=0;for(f=b.length;d<f;d++)c=b[d],c!=null&&c.length&&
$(c).triggerHandler("destroyed");return a.call($,b)}});d.ajax={REQUESTQUEUE:"lvpingAjaxRequestQueue",DEFAULT:"default",requestQueue:{},_queueRequest:function(a){var b;b=a[this.REQUESTQUEUE];this.requestQueue[b]||(this.requestQueue[b]=[]);this.requestQueue[b].push(a);return this}};d.ajax.request=function(a,b){var c;typeof a==="object"&&(c=[a,void 0],b=c[0]);b=b||{};b[this.REQUESTQUEUE]=b[this.REQUESTQUEUE]||this.DEFAULT;this._queueRequest(b);$.ajax(b);return this};d.array.forEach(["get","post"],function(a){return d.ajax[a]=
function(b,c,d,f){$.isFunction(c)&&(c=[f||d,c,void 0],f=c[0],d=c[1],c=c[2]);return this.request({type:a,url:b,data:c,success:d,dataType:f})}});d.ajax.getJSON=function(a,b){return this.get(a,void 0,b,"script")};d.ajax.getScript=function(a,b,c){return this.get(a,b,c,"json")};d.array.forEach("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a){return d.ajax[a]=function(b,c,d){var f;b=$(b);$.isFunction(c)&&(f=[c,void 0],d=f[0],c=f[1]);b[a](function(a,b,f){if(!(c&&f[this.REQUESTQUEUE]!==
c))return d(a,b,f)});return this}})}).call(this,this.lvping);
